//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public string EventDesc { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string NumberOfDays { get; set; }
        public string LocationAddress { get; set; }
        public string EstimatedTotal { get; set; }
        public string AdditionalRequirements { get; set; }
        public int CarID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
