//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int CarID { get; set; }
        public string CarType { get; set; }
        public string VehicleName { get; set; }
        public string Location { get; set; }
        public string CountryOfMan { get; set; }
        public string Seats { get; set; }
        public string ExColour { get; set; }
        public string InColour { get; set; }
        public string Condition { get; set; }
        public string Available { get; set; }
        public string Convertible { get; set; }
        public string AddInfo { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
